Fixed the bug in the description
Error: Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.u.email' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    at PromisePool.query (/opt/render/project/src/bonk-store/node_modules/mysql2/lib/promise/pool.js:36:22)
    at /opt/render/project/src/bonk-store/server.js:70:37
    at Layer.handle [as handle_request] (/opt/render/project/src/bonk-store/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/render/project/src/bonk-store/node_modules/express/lib/router/route.js:149:13)
    at authorizeStaff (/opt/render/project/src/bonk-store/server.js:59:5)
    at Layer.handle [as handle_request] (/opt/render/project/src/bonk-store/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/render/project/src/bonk-store/node_modules/express/lib/router/route.js:149:13)
    at /opt/render/project/src/bonk-store/server.js:49:9
    at /opt/render/project/src/bonk-store/node_modules/jsonwebtoken/verify.js:261:12
    at getSecret (/opt/render/project/src/bonk-store/node_modules/jsonwebtoken/verify.js:97:14) {
  code: 'ER_WRONG_FIELD_WITH_GROUP',
  errno: 1055,
  sql: '\n' +
    '            SELECT o.id_order, o.total_amount, o.status, o.created_at, \n' +
    '                   u.name as client_name, u.email as client_email,\n' +
    '                   COUNT(oi.id_order_item) as total_items\n' +
    '            FROM orders o\n' +
    '            JOIN users u ON o.id_user = u.id_user\n' +
    '            LEFT JOIN order_items oi ON o.id_order = oi.id_order\n' +
    '            GROUP BY o.id_order\n' +
    '            ORDER BY o.created_at DESC\n' +
    '        ',
  sqlState: '42000',
  sqlMessage: "Expression #6 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.u.email' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"
}